//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema001.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class employees
    {
        
        public int employeeid { get; set; }
        [DisplayName("Departamento")]
        public int departmentId { get; set; }
        [DisplayName("Nombre")]
        public string emp_Name { get; set; }
        [DisplayName("Direcciòn")]
        public string emp_Address { get; set; }
        [DisplayName("Telèfono")]
        public string emp_Phone { get; set; }
    
        public virtual departments departments { get; set; }
    }
}
